apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-kafka-quality-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-kafka-quality-manager
  template:
    metadata:
      labels:
        app: redis-kafka-quality-manager
    spec:
      containers:
      - name: redis-kafka-quality-manager
        image: your-registry/redis-kafka-quality-manager:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: Kafka__BootstrapServers
          value: "kafka-service.kafka:9092"
        - name: Redis__Host
          value: "redis-service.redis"
        - name: Processing__VideoProcessingServicesCount
          value: "10"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-kafka-quality-manager
spec:
  selector:
    app: redis-kafka-quality-manager
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
